/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c6c5d4",
        "on-tertiary-container": "#ec7700",
        "on-tertiary": "#502400",
        "surface-container-highest": "#333537",
        "on-secondary-fixed-variant": "#343d96",
        "surface-dim": "#121416",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "outline": "#908f9d",
        "tertiary": "#ffb786",
        "on-surface": "#e2e2e5",
        "surface-container-high": "#282a2c",
        "on-background": "#e2e2e5",
        "on-tertiary-fixed-variant": "#723600",
        "surface-container": "#1e2022",
        "secondary-fixed-dim": "#bdc2ff",
        "on-secondary": "#1b247f",
        "on-primary-container": "#ff645c",
        "on-secondary-fixed": "#000767",
        "tertiary-fixed-dim": "#ffb786",
        "surface-bright": "#37393b",
        "primary": "#ffb3ac",
        "on-primary": "#680008",
        "background": "#121416",
        "surface-container-low": "#1a1c1e",
        "on-error": "#690005",
        "surface-container-lowest": "#0c0e10",
        "tertiary-fixed": "#ffdcc6",
        "on-primary-fixed": "#410003",
        "primary-container": "#670008",
        "surface-tint": "#ffb3ac",
        "on-tertiary-fixed": "#311300",
        "on-secondary-container": "#a8afff",
        "secondary-fixed": "#e0e0ff",
        "surface-variant": "#333537",
        "inverse-surface": "#e2e2e5",
        "surface": "#121416",
        "primary-fixed-dim": "#ffb3ac",
        "on-primary-fixed-variant": "#930010",
        "inverse-primary": "#ba1a20",
        "inverse-on-surface": "#2f3133",
        "tertiary-container": "#4f2400",
        "on-error-container": "#ffdad6",
        "outline-variant": "#454652",
        "secondary-container": "#343d96",
        "secondary": "#bdc2ff",
        "primary-fixed": "#ffdad6"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
